name: Deploy EECE798N Project

on:
  push:
    branches: [ "main" ]
    paths:
      - 'EECE798N_Project/**'
  workflow_dispatch:

env:
  DOCKERHUB_REPO_PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}/eece798n
  PROJECT_DIR: EECE798N_Project

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['frontend', 'backend', 'database']
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}